config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                                  root GET    /                                                                                        pages#home
#                     poll_send_invites POST   /polls/:poll_id/send_invites(.:format)                                                   polls#send_invites
#                                 polls POST   /polls(.:format)                                                                         polls#create
#                              new_poll GET    /polls/new(.:format)                                                                     polls#new
#                                  poll GET    /:slug(.:format)                                                                         polls#show
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :polls, only: %I[new create] do
    post :send_invites
  end

  resource :polls, as: :poll, path: '/:slug', only: %I[show]

  resources :proposals, only: %I[create]
end

app/models/poll.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: polls
#
#  id            :bigint           not null, primary key
#  due_at        :datetime
#  scheduled_at  :datetime
#  slug          :string
#  status        :string           default("pending")
#  title         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  created_by_id :integer
#
# Indexes
#
#  index_polls_on_slug  (slug) UNIQUE
#
class Poll < ApplicationRecord
  belongs_to :created_by, class_name: 'User', inverse_of: :polls

  has_many :proposals, dependent: :destroy

  validates :title, presence: true
  validates :slug, presence: true, uniqueness: { case_sensitive: false }
  validates :scheduled_at, presence: true, timeliness: { after: :due_at, type: :datetime }
  validates :due_at, presence: true, timeliness: { before: :scheduled_at, after: Time.current, type: :datetime }

  validate :scheduled_at_after_now
  validate :due_at_after_now

  enum status: { pending: 'pending', voting: 'voting', closed: 'closed', canceled: 'canceled' }

  after_initialize :init_slug, if: :new_record?

  private

  def init_slug
    self.slug = loop do
      new_slug = SecureRandom.hex(10)
      break new_slug unless Poll.exists?(slug: new_slug)
    end
  end

  def scheduled_at_after_now
    validates_datetime :scheduled_at, after: Time.current
  end

  def due_at_after_now
    validates_datetime :due_at, after: Time.current
  end
end

app/controllers/polls_controller.rb
# frozen_string_literal: true

class PollsController < ApplicationController
  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(**poll_params, created_by: current_user)

    if @poll.save
      redirect_to poll_path(@poll.slug)
    else
      render :new
    end
  end

  def show
    @poll = Poll.includes(:created_by).find_by(slug: params[:slug])
  end

  def send_invites
    @poll = Poll.find_by(slug: params[:poll_id])
    emails = invite_params.split(';')
    emails.each do |email|
      PollMailer.with(user: current_user, recipient: email, poll: @poll).send_invite.deliver_later
    end
    redirect_to poll_path(@poll.slug), notice: "Email(s) d'invitation bien envoyé(s)"
  end

  private

  def poll_params
    params.require(:poll).permit(
      :title,
      :scheduled_at,
      :due_at,
    )
  end

  def invite_params
    params.require(:invite).require(:emails)
  end
end

app/views/polls/_invite_modal.html.haml
-# frozen_string_literal: true
#emailInviteModal.modal.fade{aria: {hidden: "true",labelledby: "emailInviteModalLabel"}, role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-lg{role: "document"}
    .modal-content
      .modal-header
        %h5#emailInviteModalLabel.modal-title Envoyer des invitations par email
        %button.close{aria: {label: "Close"}, data: {dismiss: "modal"}, type: "button"}
          %span{aria: {hidden: "true"}} ×
      .modal-body
        = simple_form_for :invite, url: poll_send_invites_path(poll.slug), html: {id: 'inviteForm', data: {controller: 'form', target: 'form.form'}} do |f|
          %h6 Emails des collègues à inviter
          = f.input :emails, as: :hidden, input_html: {data: {target: 'form.hiddenField'}}
          %div{data: {target: 'form.template'}}
            .input-group.mb-3
              %input.form-control.string.email.required{data: {target: "form.input"}, :placeholder => "toto@toto.com", :type => "email"}
              .input-group-append
                %button.btn.btn-danger{data: {action: 'form#removeField', target: 'form.removeFieldBtn'}}
                  %i.fas.fa-times
          %button.btn.btn-primary.mb-3{data: {target: 'form.addFieldBtn', action: 'form#addField'}} Ajouter un email
          .modal-footer
            %button.btn.btn-secondary{data: {dismiss: "modal"}, type: "button"} Close
            = f.submit "Envoyer l'invitation", class: 'btn btn-primary', data: {action: 'form#submit'}

app/views/polls/_proposals.html.haml
-# frozen_string_literal: true
%h4.mt-5 Propositions
.row{data: {controller: 'proposal', proposal_create_url: proposals_path, proposal_poll_slug: poll.slug, action: "google-maps-callback@window->proposal#initMap ajax:success->proposal#append"}}
  .col-12.col-md-6
    .input-group.mb-3
      %input.form-control{data: {target: 'proposal.search', action: "keydown->proposal#keydown"}, placeholder: "Cherchez une addresse ou le nom d'un restaurant"}
      .input-group-append
        %button.btn.btn-primary{data: {target: 'proposal.btn', action: 'proposal#validate'}} Valider
  
    = render 'proposals/list', proposals: poll.proposals

  .col-12.col-md-6#map{data: {target: 'proposal.map'}}

app/views/polls/new.html.haml
-# frozen_string_literal: true
.container
  %h1.text-center Créer un vote

  = simple_form_for @poll do |f|
    = f.input :title
    = f.input :scheduled_at, as: :string, input_html: { data: { controller: "flatpickr", flatpickr_date_format: "d/m/Y H:i", flatpickr_min_date: Time.current, flatpickr_min_time: l(Time.current, format: :hours) } }
    = f.input :due_at, as: :string, input_html: { data: { controller: "flatpickr", flatpickr_date_format: "d/m/Y H:i", flatpickr_min_date: Time.current, flatpickr_min_time: l(Time.current, format: :hours) } }
    = f.submit 'Créer le vote', class: 'btn btn-primary'

app/views/polls/show.html.haml
-# frozen_string_literal: true
.container{data: {controller: 'poll', poll: {end_time: @poll.due_at}}}
  #poll-infos.text-center.col.mb-5
    %h1= @poll.title
    %p.m-0 Le #{l(@poll.scheduled_at)}
    %p.m-0 Proposé par #{@poll.created_by.full_name}
  .row
    #clock.col-12.col-md-6.text-center
      %p Durée restante pour le vote
      %p{style: 'font-family: monospace; font-size: 1.1rem; font-weight: bold;', data: {target: 'poll.clock'}}
        %span{data: {target: 'poll.days'}}
        jour(s)
        %span{data: {target: 'poll.hours'}}
        heure(s)
        %span{data: {target: 'poll.minutes'}}
        minute(s)
        %span{data: {target: 'poll.seconds'}}
        seconde(s)
    #invite.col-12.col-md-6
      %section.text-center
        %h4 Invitez vos collègues avec ce lien
        .input-group.mb-3{data: {controller: 'clipboard', clipboard: {copied_text: 'Copié'}}}
          %input.form-control{value: poll_url(@poll.slug), readonly: true, data: {target: 'clipboard.source'}, "aria-describedby" => "basic-addon2", "aria-label" => "Recipient's username"}/
          .input-group-append
            %button.btn.btn-primary{data: {action: 'clipboard#copy', target: 'clipboard.btn'}} Copier
        %button.btn.btn-primary{"data-target" => "#emailInviteModal", "data-toggle" => "modal", :type => "button"}
          Envoyer des invitations par email
  = render 'polls/proposals', poll: @poll
= render 'polls/invite_modal', poll: @poll